Import Libraries

In [ ]:
import pandas as pd
import numpy as np

Import CSV dataframe

In [ ]:
Hill_Valley = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Hill%20Valley%20Dataset.csv')

In [ ]:
Hill_Valley.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Columns: 101 entries, V1 to Class
dtypes: float64(100), int64(1)
memory usage: 956.5 KB


In [ ]:
Hill_Valley.describe

<bound method NDFrame.describe of             V1        V2        V3        V4        V5        V6        V7  \
0        39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1         1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2     68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3     44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4         5.70      5.40      5.28      5.38      5.27      5.61      6.00   
...        ...       ...       ...       ...       ...       ...       ...   
1207     13.00     12.87     13.27     13.04     13.19     12.53     14.31   
1208     48.66     50.11     48.55     50.43     50.09     49.67     48.95   
1209  10160.65   9048.63   8994.94   9514.39   9814.74  10195.24  10031.47   
1210     34.81     35.07     34.98     32.37     34.16     34.03     33.31   
1211   8489.43   7672.98   9132.14   7985.73   8226.85   8554.28   8838.87   

            V8        V9     

#define target (y) and features (X)

In [ ]:
Hill_Valley.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       ...
       'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100',
       'Class'],
      dtype='object', length=101)

In [ ]:
Hill_Valley.head()

V1        V2        V3        V4        V5        V6        V7  \
0     39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1      1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2  68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3  44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4      5.70      5.40      5.28      5.38      5.27      5.61      6.00   

         V8        V9       V10  ...       V92       V93       V94       V95  \
0     39.53     38.81     38.79  ...     36.62     36.92     38.80     38.52   
1      1.70      1.75      1.78  ...      1.80      1.79      1.77      1.74   
2  73268.61  74465.84  72503.37  ...  73438.88  71053.35  71112.62  74916.48   
3  37668.32  40980.89  38466.15  ...  42625.67  40684.20  46960.73  44546.80   
4      5.38      5.34      5.87  ...      5.17      5.67      5.60      5.94   

        V96       V97       V98       V99      V100  Class  
0     38.07     36.73     39.46     37.50     39.10      0  
1      1.74      1.80      1.78      1.75      1.69      1  
2  72571.58  66348.97  71063.72  67404.27  74920.24      1  
3  45410.53  47139.44  43095.68  40888.34  39615.19      0  
4      5.73      5.22      5.30      5.73      5.91      0  

[5 rows x 101 columns]

In [ ]:
X = Hill_Valley.drop(['Class'],axis=1)

In [ ]:
y = Hill_Valley['Class']

In [ ]:
X.describe

<bound method NDFrame.describe of             V1        V2        V3        V4        V5        V6        V7  \
0        39.02     36.49     38.20     38.85     39.38     39.74     37.02   
1         1.83      1.71      1.77      1.77      1.68      1.78      1.80   
2     68177.69  66138.42  72981.88  74304.33  67549.66  69367.34  69169.41   
3     44889.06  39191.86  40728.46  38576.36  45876.06  47034.00  46611.43   
4         5.70      5.40      5.28      5.38      5.27      5.61      6.00   
...        ...       ...       ...       ...       ...       ...       ...   
1207     13.00     12.87     13.27     13.04     13.19     12.53     14.31   
1208     48.66     50.11     48.55     50.43     50.09     49.67     48.95   
1209  10160.65   9048.63   8994.94   9514.39   9814.74  10195.24  10031.47   
1210     34.81     35.07     34.98     32.37     34.16     34.03     33.31   
1211   8489.43   7672.98   9132.14   7985.73   8226.85   8554.28   8838.87   

            V8        V9     

In [ ]:
y.describe

<bound method NDFrame.describe of 0       0
1       1
2       1
3       0
4       0
       ..
1207    1
1208    0
1209    1
1210    1
1211    0
Name: Class, Length: 1212, dtype: int64>

# Step 4 : train test split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8, random_state=500)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((969, 100), (243, 100), (969,), (243,))

In [ ]:
X_train.describe

<bound method NDFrame.describe of            V1       V2       V3       V4       V5       V6       V7       V8  \
1131  2077.14  2084.11  2142.93  2170.77  1986.74  2015.91  2153.25  2251.54   
1134     1.43     1.38     1.43     1.30     1.39     1.36     1.39     1.35   
986   1709.68  1720.58  1678.19  1668.59  1642.89  1650.17  1737.15  1786.63   
702     55.58    56.30    55.43    59.93    60.34    66.80    57.47    55.53   
556    937.16   911.29   916.78   924.76   880.86   922.06   923.83   913.22   
...       ...      ...      ...      ...      ...      ...      ...      ...   
287    383.10   346.45   348.90   343.38   361.13   377.26   338.69   389.05   
957     13.15    13.96    14.30    13.88    13.56    13.58    13.38    15.34   
273    994.68  1067.63  1084.82  1126.69  1000.68  1094.84  1107.99  1084.77   
951   1350.72  1309.81  1322.77  1339.27  1302.15  1349.05  1352.76  1325.61   
858    333.72   321.45   327.34   337.40   329.44   308.52   325.69   329.46   

     

In [ ]:
y_train.describe

<bound method NDFrame.describe of 1131    1
1134    0
986     0
702     0
556     0
       ..
287     1
957     1
273     0
951     1
858     0
Name: Class, Length: 969, dtype: int64>

# Step 5 : select model

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=500)

# Step 6 : train or fit model

In [ ]:
model.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=500)

In [ ]:
model.intercept_

array([-0.02637403])

In [ ]:
model.coef_

array([[-1.18717076, -1.00102425, -0.86491458, -0.68063915, -0.88964698,
        -0.52195606, -0.13853837, -0.45448285,  0.12706159,  0.59387167,
         0.59422809,  0.4686366 ,  0.12709748,  0.35341693,  0.63039742,
        -0.0480068 , -0.01917269,  0.31377789,  0.1429656 , -0.02037524,
        -0.00565735,  0.14190679,  0.21389185,  0.0600094 ,  0.08552031,
         0.14791942, -0.04492062,  0.20647047,  0.27241811,  0.08163803,
         0.16383753,  0.16188805,  0.06747879, -0.07588586,  0.25151305,
         0.2532579 ,  0.13821489, -0.09904004,  0.09034718,  0.02841195,
         0.3856093 ,  0.04485797, -0.08905503,  0.41503043,  0.2492553 ,
         0.0610018 , -0.02504627,  0.07029599, -0.2058895 ,  0.32729332,
         0.16900498,  0.02723009, -0.0886743 ,  0.48462666,  0.39768099,
         0.09538852,  0.31137637,  0.11987357, -0.35340803, -0.08861354,
         0.08861217,  0.05857617,  0.04159892,  0.15361261,  0.02974856,
         0.12307709,  0.28204348, -0.13600031, -0.0

# Predict the model

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1])

# Accuracy of the model

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

confusion_matrix(y_test,y_pred)

array([[125,   5],
       [  3, 110]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9670781893004116

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       130
           1       0.96      0.97      0.96       113

    accuracy                           0.97       243
   macro avg       0.97      0.97      0.97       243
weighted avg       0.97      0.97      0.97       243

